name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: |
          set -a
          source __tests__/testing.env
          npm test
      - name: Build
        run: npm run build
